name: Map checks

on:
  push:
    paths:
      - "lq1/maps/src/dm/**.map"
      - "lq1/maps/src/e?/**.map"
  pull_request:
    paths:
      - "lq1/maps/src/dm/**.map"
      - "lq1/maps/src/e?/**.map"
  workflow_dispatch:

env:
  REVIEWDOG_REPORTER: "github-check"

jobs:
  lint-map-files:
    name: Lint map files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.11
      - uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f
      - name: Set reviewdog reporter
        run: |
          if [[ "${{ github.event.type }}" == "pull_request" ]]; then
            echo "REVIEWDOG_REPORTER=github-pr-check" >> $GITHUB_ENV
          else
            echo "REVIEWDOG_REPORTER=github-check" >> $GITHUB_ENV
          fi
      - name: Check Campaign maps
        run: python bin/py/map_checks.py lq1/maps/src/e*/*.map | reviewdog -f=pep8 -diff="git diff FETCH_HEAD" --filter-mode=file --fail-level=any
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Deathmatch maps
        run: python bin/py/map_checks.py lq1/maps/src/dm/*.map | reviewdog -f=pep8 -diff="git diff FETCH_HEAD" --filter-mode=file --fail-level=any
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
